### PR TITLE
Fix the path to find the `cpu-benchmark` and `gpu-benchmark` files

### PR DESCRIPTION
**Pull request by andersonandrei**
I was trying to run `wfbench.py` alone to understand how it works, by executing `python3 wfbench.py split_fasta_00000001 --percent-cpu 0.6 --cpu-work 400 './split_fasta_00000001_input.txt'` and I got the following problem:

```
python3 wfbench.py split_fasta_00000001 --percent-cpu 0.6 --cpu-work 400 './split_fasta_00000001_input.txt'
[WfBench] Starting split_fasta_00000001 Benchmark

[WfBench] Starting CPU and Memory Benchmarks...
['<my-path>/WfCommons/wfcommons/wfbench/cpu-benchmark', '21']
Traceback (most recent call last):
  File "<my-path>/WfCommons/wfcommons/wfbench/wfbench.py", line 254, in <module>
    main()
  File "<my-path>/WfCommons/wfcommons/wfbench/wfbench.py", line 225, in main
    cpu_procs = cpu_mem_benchmark(cpu_threads=int(10 * args.percent_cpu),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<my-path>/WfCommons/wfcommons/wfbench/wfbench.py", line 128, in cpu_mem_benchmark
    cpu_proc = subprocess.Popen(cpu_prog)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '<my-path>/WfCommons/wfcommons/wfbench/cpu-benchmark'
```

I identified that the `cpu-benchmark` is not inside the `wfbench` directory, but two directories back on `<my-path>/WfCommons/bin/. So I updated the way this path was created.

I modified the `wfbench.py` from this:
```
   cpu_prog = [f"{this_dir.joinpath('cpu-benchmark')}", f"{cpu_work_per_thread}"]
   ...
   gpu_prog = [f"CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES={device} {this_dir.joinpath('gpu-benchmark')} {work}"]

```

To this:
```
   cpu_prog = [f"{this_dir.parent.parent.joinpath('bin').joinpath('cpu-benchmark')}", f"{cpu_work_per_thread}"]
   ...
   gpu_prog = [f"CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES={device} {this_dir.parent.parent.joinpath('bin').joinpath('gpu-benchmark')} {work}"]
```

### CODE REVIEW

**Comment by rafaelfsilva** [comment]
Hi @andersonandrei, thanks for reporting this potential issue.

The problem with the proposed fix is that it will work well if you try to run `wfbench.py` as you did above, but it will fail when the script would be used within a workflow system.

After putting some thought into it, I believe one potential solution would be to move `wfbench.py` into the `bin` folder, as it is a standalone script, and then update WfCommons installation scripts.

What do you think?

**Comment by andersonandrei** [comment]
Hello @rafaelfsilva,

I see your point, I was thinking about that but I didn't get to test these cases.
I think that your proposition makes sense then.

Best,
Andrei.

**Review by rafaelfsilva — CHANGES_REQUESTED** [review]
The proposed changes would generate issues when using WfBench with workflow systems. I fix has been implemented to move `wfbench.py` to the `bin` folder.

**Comment by andersonandrei** [comment]
Thank you, I think it solves the problem.

**Review by andersonandrei — COMMENTED** [review]
It solves the problem. Thank you!

**Pull request closed without merging**
